CSI Topology support for pure volumes
libopenstorage/openstorage pull request #2011
Opened 2022-03-22 05:28 UTC by piyush-nimbalkar

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** (optional)
Closes # https://portworx.atlassian.net/browse/PWX-22501

**Special notes for your reviewer**:

2022-03-22 23:29 UTC, ggriffiths commented
@piyush-nimbalkar looks like the CSI unit tests are failing:
`github.com/libopenstorage/openstorage/csi`

Lets fix those tests and add some coverage for the csi pkg changes

2022-03-22 23:31 UTC, ggriffiths requested changes
Mostly looks good, just fix the tests and add a new one for the `CreateVolume` topology cases. Maybe add one to make sure we don't add topology info for non-pure volumes.

2022-03-24 00:01 UTC, piyush-nimbalkar commented
Fix the build and added testcases for topology.

2022-03-24 00:10 UTC, ggriffiths approved these changes

2022-03-24 00:12 UTC, merged