FA DirectAccess CreateOptions is not honored by PX
libopenstorage/openstorage pull request #2148
Opened 2022-11-07 18:49 UTC by ashinde-px

**What this PR does / why we need it**:
FA DirectAccess CreateOptions is not honoroed by PX

**Which issue(s) this PR fixes** (optional)
Closes #
PWX-23422: FA DirectAccess CreateOptions is not honoroed by PX

**Special notes for your reviewer**:

2022-11-08 20:14 UTC, ggriffiths commented on SDK_CHANGELOG.md
> +### v0.150.0 - (8/17/2022)
You'll want to keep the same versioning scheme in release-9.5:

```suggestion
### v0.101.30 - (10/26/2022)

* FA DirectAccess CreateOptions is not honoroed by PX

### v0.101.29 - (9/13/2022)

* Add NONE value to sharedv4 service type enum

### v0.101.28 - (8/18/2022)
```

2022-11-08 20:15 UTC, ggriffiths commented on api/api.proto
> +    Patch = 0;
This should be 
v0.101.30:

Minor = 101
Patch = 30

2022-11-08 20:16 UTC, ggriffiths requested changes
@ashinde-px you'll want to re-run `make docker-proto` after addressing the above concerns

2022-11-09 18:18 UTC, ggriffiths commented
Looks like `github.com/libopenstorage/openstorage/cli` unit tests are failing now.

2022-11-15 10:37 UTC, ashinde-px commented
> Looks like `github.com/libopenstorage/openstorage/cli` unit tests are failing now.

Fixed the issue.

2022-11-15 17:55 UTC, ggriffiths approved these changes

2022-11-16 16:00 UTC, merged