feat: delete cloud backup handler
libopenstorage/openstorage pull request #2304
Opened 2023-07-28 05:35 UTC by Glitchfix

**What this PR does / why we need it**:
Delete snapshots created for cloud backup

the deletion would require passing in the credential id in the secrets parameter along with the cloud backup id as the snapshot id

2023-07-28 17:10 UTC, ggriffiths commented on csi/controller.go
> +	_, locator, _, err := s.specHandler.SpecFromOpts(req.GetSecrets())
Can we pass locator that we already got on line 1088? Instead of fetching a new copy

2023-07-28 17:12 UTC, ggriffiths commented on csi/controller.go
> +	if err != nil {
Check for NotFound error here and return `return &csi.DeleteSnapshotResponse{}, nil` in case the underlying snapshot was deleted.

2023-07-28 17:14 UTC, ggriffiths commented on csi/controller.go
> +	return nil, status.Errorf(codes.Aborted, "unexpected error occured: %v", err)
This can just be simplified to `return nil`.

If we didn't get an error on line 1160, we know deleted succeeded and `err` will be nil.

2023-07-28 17:15 UTC, ggriffiths commented on csi/controller_test.go
> +			"volume id not found while creating",
should say while deleting

2023-07-28 17:15 UTC, ggriffiths commented on csi/controller_test.go
> +			true,
This should not return an error

2023-08-14 19:17 UTC, ggriffiths commented on csi/controller.go
> +	if err != nil {
Can we check similar to this line?
https://github.com/libopenstorage/openstorage/blob/master/csi/controller.go#L154

We want to check the actual status code

2023-08-14 20:55 UTC, ggriffiths commented on csi/controller.go
> +	if err != nil {
String check is error prone, we want to check for actual status code.

2023-08-16 18:38 UTC, ggriffiths requested changes
A few changes still required. @Glitchfix can you also post testing output when you get a chance?

2023-08-16 23:12 UTC, Glitchfix commented
> A few changes still required. @Glitchfix can you also post testing output when you get a chance? Please re-request review here when ready

```
go test -timeout 30s -run ^TestOsdCsiServer_listCloudSnapshots$ github.com/libopenstorage/openstorage/csi
ok      github.com/libopenstorage/openstorage/csi       
```

2023-08-17 00:12 UTC, ggriffiths commented
@Glitchfix I mean integration testing - have we built a PX container with above changes and tried creating/deleting cloud snapshots?

2023-12-28 01:47 UTC, closed without merging