PWX-27646: Block cloudsnaps on FA direct access volumes
libopenstorage/openstorage pull request #2321
Opened 2023-08-11 10:01 UTC by ashinde-px

**What this PR does / why we need it**:
Block cloudsnaps on FA direct access volumes

**Which issue(s) this PR fixes** (optional)
Closes #PWX-27646

**Special notes for your reviewer**:

2023-08-11 10:01 UTC, ashinde-px commented
Updated testing results in the ticket comment : https://portworx.atlassian.net/browse/PWX-27646

2023-08-11 10:30 UTC, rkinhalkar-px approved these changes

2023-08-14 19:07 UTC, ggriffiths commented on csi/controller.go
> +		return nil, status.Errorf(codes.InvalidArgument, "cloudsnap feature is not supported for pure volumes")
nit:
```suggestion
		return nil, status.Errorf(codes.InvalidArgument, "cloudsnaps are not supported for pure volumes")
```

2023-08-16 16:00 UTC, ashinde-px commented on csi/controller.go
> +		return nil, status.Errorf(codes.InvalidArgument, "cloudsnap feature is not supported for pure volumes")
Done.

2023-08-16 16:12 UTC, adityadani requested changes
@ashinde-px This specific change for taking cloud backups through CSI snapshots has not been released yet. To block cloudsnaps on FA volumes, you need to make a change in porx so that you block cloudsnap creation triggered through CLI (and not CSI)

2023-08-17 04:29 UTC, ashinde-px commented
> @ashinde-px This specific change for taking cloud backups through CSI snapshots has not been released yet. To block cloudsnaps on FA volumes, you need to make a change in porx so that you block cloudsnap creation triggered through CLI (and not CSI)

Hi @adityadani sure let me create PR at porx side then to block request from CLI, was waited to merge this PR so that to add both changes at once. Closing this PR as its not required.

2023-08-18 16:07 UTC, closed without merging

2023-08-18 16:08 UTC, ashinde-px commented
let me create PR at porx side then to block request from CLI, was waited to merge this PR so that to add both changes at once. Closing this PR as its not required.